### ISSUE TITLE
How to use with babel-node?

### ISSUE THREAD

**Issue by satyavh** [theoephraim/lint-fix-nodemon#3]
Really like your script, but we're using babel-node, e.g.

`nodemon --exec babel-node src/index.js`

But replacing nodemon with lint-fix-nodemon, it doesn't know how to handle --exec

Any suggestions?

**Comment by theoephraim** [comment]
Sorry for the very late reply. I had not looked at this for a while...

You should be able to customize nodemon's behaviour by passing in a config object in your package.json.
see https://github.com/remy/nodemon#packagejson

For example:
```
  "nodemonConfig": {
    "exec": "babel-node src/index.js",
    "ext": "js,json,ts",
    ...
  },
```
